import dayjs from "dayjs";

export const board = [
  {
    id: 1,
    title: "Card title 1",
    description: "Card content",
    cidade: "Londrina",
    regiao: "centro",
    status: "To Do",
    created: dayjs(),
    assignee: "John",
  },
  {
    id: 2,
    title: "Card title 2",
    description: "Card content",
    cidade: "São Paulo",
    regiao: "Zona Sul",
    status: "To Do",
    created: dayjs(),
    assignee: "John",
  },
  {
    id: 3,
    title: "Card title 3",
    description: "Card content",
    cidade: "Cambé",
    regiao: "Centro",
    status: "To Do",
    created: dayjs(),
    assignee: "John",
  },
  {
    id: 9,
    title: "Card title 9",
    description: "Card content",
    status: "In Progress",
    created: dayjs(),
    assignee: "John",
  },
  {
    id: 12,
    title: "Card title 12",
    description: "Card content",
    status: "In Progress",
    created: dayjs(),
    assignee: "John",
  },
  {
    id: 10,
    title: "Card title 10",
    description: "Card content",
    status: "Done",
    created: dayjs(),
    assignee: "John",
  },
  {
    id: 11,
    title: "Card title 11",
    description: "Card content",
    status: "Done",
    created: dayjs(),
    assignee: "John",
  },
  {
    id: 13,
    title: "Card title 13",
    description: "Card content",
    status: "Done",
    created: dayjs(),
    assignee: "John",
  }
];